"use client";

import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ChakraProvider} from '@chakra-ui/react'
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import "./globals.css";

const inter = Inter({subsets: ["latin"]});
const queryClient = new QueryClient()

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// Create a client


export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <ChakraProvider>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </ChakraProvider>
      </body>
      </html>
  );
}
