import React from "react";
import {Box, Input, InputGroup, InputLeftElement, InputRightElement, Stack, Text} from "@chakra-ui/react";
import {FaCoffee} from "react-icons/fa"

function ImageGallery() {
  return <Box>
    {/*<Stack spacing={4}>*/}
    {/*  <InputGroup>*/}
    {/*    <InputLeftElement pointerEvents='none'>*/}
    {/*      <FaCoffee color='gray.300' />*/}
    {/*    </InputLeftElement>*/}
    {/*    <Input type='tel' placeholder='Phone number' />*/}
    {/*  </InputGroup>*/}

    {/*  <InputGroup>*/}
    {/*    <InputLeftElement pointerEvents='none' color='gray.300' fontSize='1.2em'>*/}
    {/*      $*/}
    {/*    </InputLeftElement>*/}
    {/*    <Input placeholder='Enter amount' />*/}
    {/*    <InputRightElement>*/}
    {/*      <FaCoffee color='green.500' />*/}
    {/*    </InputRightElement>*/}
    {/*  </InputGroup>*/}
    {/*</Stack>*/}

    <Text className={"darkmode_text_normal"} fontWeight={700}>Liked by You</Text>
    <Text className={"darkmode_text_normal"} fontWeight={700}>Generated by You</Text>
    <Text className={"darkmode_text_normal"} fontWeight={700}>Generated by others (Public)</Text>
  </Box>
}

export default ImageGallery;