import {Inter} from 'next/font/google';

import '../globals.css';

const inter = Inter({subsets: ['latin']});

// Create a client
import '@mantine/core/styles.css';
import React from 'react';
import {Metadata} from 'next';

export const metadata: Metadata = {
	title: 'Yin\'s Dashboard | The All-In-One Configurator for Yin.',
	description:
		'Here, you can view and manage images generated by you and other discord' +
		' users.' + ' openGraph You can set the default visibility of your' +
		' profile and prompts. You can add and edit chatbot personas for Yin.'
	,
	openGraph: {
		url: 'https://avatars.githubusercontent.com/u/44526763?v=4',
		title: 'Yin | Chatbot and Prompt Assistant',
		description: 'Create and interact with multiple chatbot personas ◆ Generate AI images using Dall-E and Stable Diffusion ◆ Customise your assistant with unique personality.',
		images: [
			{
				url: 'https://avatars.githubusercontent.com/u/44526763?v=4',
				width: 800,
				height: 600,
				alt: 'Og Image Alt',
				type: 'image/jpeg'
			},
			{
				url: 'https://avatars.githubusercontent.com/u/44526763?v=4',
				width: 900,
				height: 800,
				alt: 'Og Image Alt Second',
				type: 'image/jpeg'
			}
		],
		siteName: 'SiteName'
	}
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body className={inter.className}>
		{children}
		</body>
		</html>
	);
}
