service: yin-backend-prod
#service: yin-backend-dev
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  timeout: 29
  httpApi:
    cors: true
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - "s3:GetObjectAcl"
            - "s3:PutObject"
            - "s3:PutObjectAcl"
            - "s3:DeleteObject"
          Resource: '*'
#            - 'arn:aws:s3:::yin-storage-dev/*'
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
package:
  individually: false
  include:
    - "node_modules/.prisma/**"

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false
    packager: 'npm'
functions:
  discordAskPrompt:
    handler: routes/chat-prompt.main
    events:
      - httpApi:
          path: /discord/chat-prompt
          method: any
  discordImagePrompt:
    handler: routes/image-prompt.main
    events:
      - httpApi:
          path: /discord/image-prompt
          method: any
  userResourceRoute:
    handler: routes/user.getGallery
    events:
      - httpApi:
          path: /user/{resource} # gallery
          method: any
  getRecentImagePrompts:
    handler: routes/global.getRecentImagePrompts
    events:
      - httpApi:
          path: /recent/image-prompts # discord-oauth
          method: any
  getGuild:
    handler: routes/global.getGuildPermissions
    events:
      - httpApi:
          path: /guild/{id} # discord-oauth
          method: any